SELECT ID, TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE) AS month_count
FROM project
WHERE TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE) = (
    SELECT MAX(TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE))
    FROM project
);